### ISSUE TITLE
Failure of import statement

### ISSUE THREAD

**Issue by Veekshit** [znwang25/fuzzychinese#6]
Hi trying to utilize this package to compare Chinese characters and get their match score, but faced following error in import statement.

>>> import fuzzychinese
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/fuzzychinese/__init__.py", line 1, in <module>
    from ._fuzzy_chinese_match import FuzzyChineseMatch
  File "/usr/local/lib/python2.7/site-packages/fuzzychinese/_fuzzy_chinese_match.py", line 109
    f'Cannot find analyzer \'{self.analyzer}\', use default stroke analyzer instead.'

Can someone please make me understand the issue here and help in resolving it. Thanks

**Comment by znwang25** [comment]
Hi @Veekshit ,
This seems to be an incompatibility issue with python 2.7. I recommend you to update your python to the latest version. FYI, Python 2 is no longer supported by the Python Foundation since the beginning of this year.
